[package]
name = "whisker"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/aonyx-ai/whisker.git"
publish = false

[[bin]]
name = "whisker"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
anyhow = "1"
clawless = "0.6.0"
etcetera.workspace = true
gix.workspace = true
gix-url.workspace = true
ignore.workspace = true
libloading.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
whisker-core = { path = "../whisker-core" }
whisker-reporting = { path = "../whisker-reporting" }
whisker-rust = { path = "../whisker-rust" }
whisker-types = { path = "../whisker-types" }

[dev-dependencies]
assert_cmd = "2"
predicates = "3"
tempfile.workspace = true
toml.workspace = true
trycmd = "1.0"
