import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// The pages are a flat sequence, ordered by the `sidebar_position` each one
// declares.
const sidebars: SidebarsConfig = {
  docsSidebar: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
