[package]
name = "whisker-types"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
tree-sitter.workspace = true

[dev-dependencies]
proptest.workspace = true
tree-sitter-rust.workspace = true

[build-dependencies]
rustc_version.workspace = true

[lints]
workspace = true
